language: python

sudo: false

python:
  - "2.7"

install: pip install --use-mirrors flake8

before_script: flake8 .

script: python setup.py test

deploy:
  provider: pypi
  user: azavea
  password:
    secure: S4FQSkKrvNl+D+w/2hMBKf2DWmk0naC44/YMmDODsmJ0Te9iP7zs2pS9RQ9rWA9mcRMSEK3yTLcPvRTA0MBYIKcDmhCjKRNMSy/vEVtbP6+/WH+gFZvO/yq1wz/illmY6PQeN90enPOiJFff2Q5BDRRNk9zZ5yfML8bLvkJZn6A=
  distributions: "sdist bdist_wheel"
  skip_cleanup: true
  on:
    repo: azavea/majorkirby
    tags: true
