dist: xenial
language: python
python:
  - "3.7"

before_install: sudo rm /etc/boto.cfg

install: pip install flake8 black

before_script:
  - flake8 .
  - black --check .

script: python setup.py test

deploy:
  provider: pypi
  user: azavea
  password:
    secure: hY5D8BDgtPYPTrodOxyGirEK+qui+RFTYl6nJ4jyVjsR2WY45VLkYnetphFkIlQv3qNAuyEwuIQ/9eHsFOV6Sprc5Rlp4GdqdXn7rxkvvQebk+gjdcqvcZUPElux3OD77uuCQn+tvhlo9sueAOb+G4Ir6P9P+81JU2FHG79Bpoc=
  distributions: "sdist bdist_wheel"
  skip_cleanup: true
  on:
    repo: azavea/majorkirby
    tags: true
